seed: 1234
tag: lora_ensemble
log_dir: ./output

model_type: 'dino_vitbase16,clip_vitb16,open_clip_vitb16'
feat_type: 'cls,embedding,embedding'
stride: '16,16,16'
use_lora: True

dataset_root: /share/portal/aw588/finetuning/data # should have a finetuning/data/ in this folder
num_cpu_workers: 4

lr: 0.0003
weight_decay: 0.0
batch_size: 16
epochs: 6
margin: 0.05

lora_r: 16
lora_alpha: 0.5
lora_dropout: 0.3