tag: resnet_ensemble
checkpoint: 
  - /share/portal/wph52/models/joint_pred/train_logs/default/2024-09-23-031938_model=resnet_linear_xpos=True_datajoints_xpos_seq_startpt=True_freezebackbone=True_lr=0.008nt=None/checkpoints/best_model_epoch_43.pth
  - /share/portal/wph52/models/joint_pred/train_logs/default/2024-09-23-024112_model=resnet_linear_xpos=True_datajoints_xpos_seq_startpt=True_freezebackbone=True_lr=0.008nt=None/checkpoints/best_model_epoch_47.pth
  - /share/portal/wph52/models/joint_pred/train_logs/default/2024-09-23-020231_model=resnet_linear_xpos=True_datajoints_xpos_seq_startpt=True_freezebackbone=True_lr=0.008nt=None/checkpoints/best_model_epoch_47.pth
  - /share/portal/wph52/models/joint_pred/train_logs/default/2024-09-23-012135_model=resnet_linear_xpos=True_datajoints_xpos_seq_startpt=True_freezebackbone=True_lr=0.008nt=None/checkpoints/best_model_epoch_47.pth
  - /share/portal/wph52/models/joint_pred/train_logs/default/2024-09-23-004257_model=resnet_linear_xpos=True_datajoints_xpos_seq_startpt=True_freezebackbone=True_lr=0.008nt=None/checkpoints/best_model_epoch_49.pth
  
start_from_pretrained: True
freeze_backbone: False
target_joint_pos: null
output_dim: 54 # 18 joints * 3 dimensions each for joint geom xpos pos data
seed: 1234
lr: .1
momentum: 0.875
epochs: 40
batch_size: 16
num_cpu_workers: 6
margin: 0.05