tag: resnet_reco
start_from_pretrained: True
freeze_backbone: True
checkpoint: null
target_joint_pos: null
output_dim: 54 # 18 joints * 3 dimensions each for joint geom xpos pos data
seed: 1234
lr_joints: .032
lr_reco: .016
epochs: 40
batch_size: 16
momentum: 0.875

# Not used
lr: .1
num_cpu_workers: 6
margin: 0.05