tag: resnet_linear
start_from_pretrained: True
freeze_backbone: False
checkpoint: null
target_joint_pos: null
output_dim: 54 # 18 joints * 3 dimensions each for joint geom xpos pos data
seed: 1234
lr: .1
momentum: 0.875
epochs: 40
batch_size: 16
num_cpu_workers: 6
margin: 0.05