run_notes: null
run_type: default
test: False

defaults:
  - training: resnet_linear
  - data: ft_joints_xpos
  - _self_

logging:
  model_save_freq: 100  # Frequency to save the model

  wandb_project: ft
  wandb_mode: online # disabled
  wandb_tags: []

  run_name: null
  run_path: null

hydra:
  run:
    dir: ./train_logs/${run_type}/${now:%Y-%m-%d-%H%M%S}_model=${training.tag}_xpos=${data.use_xpos}_data=${data.name}_startpt=${training.start_from_pretrained}_freezebackbone=${training.freeze_backbone}_lr=${training.lr}nt=${run_notes}